### ISSUE TITLE
Invalid operation. Please check your configuration. OAuth2 authorization servers does notsupport /userinfo endpoint.

### ISSUE THREAD

**Issue by kuldip9060** [okta/samples-js-react-native#34] opened 2020-03-07 07:27 UTC
Getting Error: "**Invalid operation. Please check your configuration. OAuth2 authorization servers does notsupport /userinfo endpoint**" When try to login with android emulator/device only this same thing is working fine with ios simulator/device and getting this error while try to access loggedin userinfo "**await getUser()**". 
here my configuration for reference.
```
oidc: {
    clientId: {My_Client_ID}',
    redirectUri: 'com.sampleapplication:/',
    endSessionRedirectUri: 'com.sampleapplication:/',
    discoveryUri: 'https://dev-493092.oktapreview.com/oauth2/default',
    scopes: ['openid', 'profile', 'offline_access'],
    requireHardwareBackedKeyStore: false,
  },
```

In Android/build.gradle file -> 
```
allprojects {
    repositories {
...
maven {
            url  "https://dl.bintray.com/okta/com.okta.android"
        }
...
}
}
```

In android/app/build.gradle file -> 

```
android {
defaultConfig {
...
manifestPlaceholders = [
                appAuthRedirectScheme: 'com.sampleapplication'
        ]
...
}
}
```

Please let me know what is happening wrong here. Thank You... K00L ;)

**Comment by swiftone** [comment] 2020-03-20 20:10
Internal ref: OKTA-283789

**Comment by jdnichollsc** [comment] 2020-04-27 22:03
Our current workaround is this:
```
const initializeOkta = () => {
  const oidc = {
    clientId: config.OKTA_CLIENT_ID,
    redirectUri: getDeepLink('callback'),
    endSessionRedirectUri: getDeepLink('logout'),
    discoveryUri: config.OKTA_ISSUER_URL + Platform.select({
      android: '/.well-known/openid-configuration',
      ios: ''
    }),
    scopes: [
      'openid',
      'profile',
      'offline_access',
      'user'
    ],
    requireHardwareBackedKeyStore: false
  }
  return createConfig({
    clientId: oidc.clientId,
    redirectUri: oidc.redirectUri,
    endSessionRedirectUri: oidc.endSessionRedirectUri,
    discoveryUri: oidc.discoveryUri,
    scopes: oidc.scopes,
    requireHardwareBackedKeyStore:
      oidc.requireHardwareBackedKeyStore
  })
}
```

**Comment by shuowu** [comment] 2020-05-02 15:33
Another workaround is you can try to set the `discoveryUri` without `/oauth2/default`, then the SDK should be able to configure it automatically.

**Comment by jdnichollsc** [comment] 2020-05-02 20:33
That workaround don't work for us because we have a custom issuerUrl, but thanks!

**Comment by swiftone** [comment] 2020-05-08 18:06
@kuldip9060 - Until we find a better solution, have you been able to use one of the workarounds shown by @shuowu or @jdnichollsc?

**Comment by shihabpadath** [comment] 2020-08-07 11:58
I also tried many ways, finally it worked suggested by @shuowu

**Comment by JayNewstrom** [comment] 2020-10-21 20:44
This was an issue with the way the [Android SDK](https://github.com/okta/okta-oidc-android) handled discovery URIs. I confirmed the fix by adding `implementation 'com.okta.android:oidc-androidx:1.0.16'` to the sample apps `build.gradle`.

When we release the next version of the [React Native SDK](https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react-native) it'll point to the fix in the Android SDK, and I'll close this issue then.

**Comment by JayNewstrom** [comment] 2020-11-10 19:09
This is fixed in `1.4.4`.

**Closed by JayNewstrom** 2020-11-10 19:09 UTC
